name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: liuhangbiao/puppeteer:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
            
    # - uses: actions/checkout@v2
    # - name: Build
    #   run: docker build . --tag liuhangbiao/puppeteer:latest
    # - name: Test
    #   run: |
    #     cd example
    #     docker-compose -f docker-compose.integration-tests.yml build tests
    #     docker-compose -f docker-compose.integration-tests.yml run tests
    #     ls screenshots/app.png
    # - uses: actions/upload-artifact@v1
    #   with:
    #     name: test-screenshot.png
    #     path: example/screenshots/app.png
